# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'composeApp', :path => '../ComposeApp'
  pod 'Firebase'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore' 
  pod 'GoogleSignIn'
  pod 'FirebaseMessaging'
  pod 'YandexMapsMobile', '4.26.1-lite'
end
